name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create config.js
        run: |
          echo "const config = {
            emailjs: {
              serviceId: '${{ secrets.EMAILJS_SERVICE_ID }}',
              publicKey: '${{ secrets.EMAILJS_PUBLIC_KEY }}',
              templateId: '${{ secrets.EMAILJS_TEMPLATE_ID }}'
            }
          };" > config.js
          cp config.js public/js/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 